### PR TITLE
Fetch layout

### PR DESCRIPTION
**Pull request by ManuelDominic**
**This pull request implements all functionality:-**
- Apart from emailing-still fixing a bug.

* Non-admin can signup as well as login.
* Non-admin can upload images/video to a given record, update/delete the record as well as create more records.
* Admin and non-admin can view the incidents plus the total number of them.
* Admin and non-admin users can view the images/videos on the record.
* Admin can view all users in the system
* Non-admin can view their profile

**How to test**
* login:
**Credentials**

* Admin Email: `ireportermanueldominic@gmail.com` Password: `admin123`
* User Email: `ematembu2@gmail.com` Password: `manuel123`

@NicholusMuwonge @Rhytah @JamesMudidi @sanya-kenneth @frankopkusianwar @AtamaZack @kalsmic @KabohaJeanMark @nadralia @reifred @llwasampijja @richien @Genza999 @3Nakajugo @e-ian @Manorlds-Eaglespark @PatrickMugayaJoel @bisonlou @v1b3m @mwinel @sebbs

### CODE REVIEW

**Comment by kalsmic** [comment]
@ManuelDominic, Work on the validation for the comment, it still shows the error even when the comment is valid.
I have tried to upload an image successfully but the image does not show.
Also when I add an image, a duplicate record is created. try using foreign keys, have a table for images, where an image is linked to the record by the record's id, this way the record can have several images without being duplicated.

**Comment by llwasampijja** [comment]
Hello @ManuelDominic , It would be better if in your future PRs you include the link to your gh-pages so that one doesn't have to browse the repo looking for it!

**Comment by llwasampijja** [comment]
@ManuelDominic Good work, you have a nice User interface. As far as signing up, I didnt go far,
When signing up with passwords that are not similar, there is no message to let the user know what they have done wrong. I dont know whether the process failed because the password was invalid or just not matching.! I failed to signup, and i dont know why as i got not message.
I failed to signup with these details:
firstname: Lamech, lastname: lwasa, username: lamech, email: lwasa@bolon.com, phone: 0789999999, password: password?
And i didn't get any message prompting me on how I can successfully signup,

**Comment by llwasampijja** [comment]
@ManuelDominic   After logging in as admin, I realized that my prior signups where successful but I didn't get any message or redirected to the login page if that is necessary.
The nonadmin login failed, please try to fix that!

**Pull request merged**
